### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by delfme** [Anees7757/quick_text#1]
Hello link is not working. Can you please have a look?
```
 QuickText(
                            'This is [link](https://www.google.com).',
                            style: const TextStyle(      
                              color: Colors.white,
                              fontSize: 13,
                              height: 1.3,
                            ), 
                            textAlign: TextAlign.center
                        ),
```

**Comment by anees7757** [comment]
Hi @delfme 
Thanks for letting me know.

Ensure you are using **latest version** and that internet permissions are properly configured for Android and iOS. After verifying, perform a full `flutter run`, as Hot Reload or Hot Restart may not reflect changes.
